name: Static Type Checker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Mypi
      uses: python/mypy@master
      with:
        install_project_dependencies: no

    - name: Run Mypi
      run: mypi combine.py
