name: Static Type Checker

on: [push]

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install and run Mypy
      uses: python/mypy@master
      with:
        options: --strict
        install_project_dependencies: no
